#include "init.h"

void GPIO_Ini_Self_Def(void)
{
    SET_BIT_SELF(RCC_AHB1ENR,RCC_GPIOBEN | RCC_GPIOCEN);
    SET_BIT_SELF(GPIOB_MODER, GPIO_PIN_7_OUT);
    SET_BIT_SELF(GPIOB_OSPEEDR, GPIO_PIN_7_MED);
    SET_BIT_SELF(GPIOB_BSRR, GPIO_PIN_7_RESET);
}

void GPIO_Ini_CMSIS(void){
    SET_BIT(GPIOB->MODER,GPIO_MODER_MODE14_0);
    CLEAR_BIT(GPIOB->OTYPER,GPIO_OTYPER_OT14);
    SET_BIT(GPIOB->OSPEEDR,GPIO_OSPEEDER_OSPEEDR14_0);
   
}