#include "Init.h"

void GPIO_Init(void){ // buttons 12, 15, 9, user // led 0, 7, 14 
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN); //Тактирование на B и C
    //SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN); 
    //Тактирование на B и C
    //SET_BIT(GPIOC->MODER, GPIO_MODER_MODE13_1);
    //CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR13_0);
    
    // SET_BIT(GPIOB->MODER, GPIO_MODER_MODE7_0); //7 pin - output
    // CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_7); //7 pin on PP
    // SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED7_0);
    // CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR7_0); // 2 - 10 

    // SET_BIT(GPIOB->MODER, GPIO_MODER_MODE8_1); 
    // CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR8_0);  

    // SET_BIT(GPIOB->MODER, GPIO_MODER_MODE8_0); //8 pin - output
    // CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_8); //8 pin on PP
    // SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED8_0);
    // CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR8_0); // 2 - 10
    // RCC_GPIO_EN |= RCC_GPIOB_EN + RCC_GPIOC_EN; //включение тактирования портов GPIOB и GPIOC

    // GPIOB_MODER |= GPIOB_MODE_PIN7_OUT; //настройка пин 7 на вывод
    // GPIOB_OTYPER |= GPIOB_OTYPE_PIN7_PP; //включение PUSH-PULL на пин 7
    // GPIOB_OSPEEDER |= GPIOB_OSPEED_PIN7_MID; //настройка средней скорости работы GPIOB пин 7 
    //GPIOB_PUPDR |= GPIOB_PUPDR_PIN7_NOPUPD; //Отключение PU/PD резисторов на пин 7
}
void GPIO_led_init(void){
    //SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN); //RCC on GPIOB
    //PB0 - green
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE0_0);  
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_0);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED0_0);
    SET_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR0_0); //0x1 - 01  10 &= ~01 => 10 &= 10 = 10
    //PB7 - blue
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE7_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_7);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED7_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR7_0);
    //PB14 - red
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE14_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_14);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED14_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR14_0);    
}

void GPIO_button_input(void){
    //PB12
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE12_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR12_0);
    //PB15
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE15_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR15_0);
    //PB9
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE9_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR9_0);
}

void GPIO_button_output(void){ //PB12, PB15, PB9
    //PB12
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE12_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_12);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED12_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR12_0);
    SET_BIT(GPIOB->BSRR, GPIO_BSRR_BS12);   
    //PB15
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE15_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_15);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED15_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR15_0);
    SET_BIT(GPIOB->BSRR, GPIO_BSRR_BS15);   
    //PB9
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE9_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_9);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED9_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR9_0);
    SET_BIT(GPIOB->BSRR, GPIO_BSRR_BS9);   
}
void button1_output(void){
    //PB12
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE12_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_12);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED12_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR12_0);
    SET_BIT(GPIOB->BSRR, GPIO_BSRR_BS12);

}
void button2_output(void){
    //PB15
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE15_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_15);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED15_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR15_0);
    SET_BIT(GPIOB->BSRR, GPIO_BSRR_BS15);
}
void button3_output(void){
    //PB9
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE9_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_9);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED9_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR9_0);
    SET_BIT(GPIOB->BSRR, GPIO_BSRR_BS9);
}
void button1_input(void){
    //PB12
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE12_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR12_0);
    //SET_BIT(GPIOB->BSRR, GPIO_BSRR_BR12);
}
void button2_input(void){
    //PB15
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE15_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR15_0);
    //SET_BIT(GPIOB->BSRR, GPIO_BSRR_BR15);
}
void button3_input(void){
    //PB9
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE9_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR9_0);
    //SET_BIT(GPIOB->BSRR, GPIO_BSRR_BR9);
}

