#include "init.h"


void GPIO_Ini(void){
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN| RCC_AHB1ENR_GPIODEN);

    /*SET_BIT(GPIOB->MODER, GPIO_MODER_MODE7_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_7);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR7_0);*/

    //VARIANT 2
    
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE13_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_13);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR13_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR13_0);

    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE12_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_12);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR12_0);

    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE15_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_15);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR15_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR15_0);

   /* SET_BIT(GPIOB->MODER, GPIO_MODER_MODE3_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_3);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR3_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR3_0);

    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE4_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_4);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR4_0);
    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR4_0);*/
    SET_BIT(GPIOD->MODER, GPIO_MODER_MODE3_0);
    CLEAR_BIT(GPIOD->OTYPER, GPIO_OTYPER_OT_3);
    SET_BIT(GPIOD->OSPEEDR, GPIO_OSPEEDER_OSPEEDR3_0);
    CLEAR_BIT(GPIOD->PUPDR, GPIO_PUPDR_PUPDR3_0);

    SET_BIT(GPIOD->MODER, GPIO_MODER_MODE4_0);
    CLEAR_BIT(GPIOD->OTYPER, GPIO_OTYPER_OT_4);
    SET_BIT(GPIOD->OSPEEDR, GPIO_OSPEEDER_OSPEEDR4_0);
    CLEAR_BIT(GPIOD->PUPDR, GPIO_PUPDR_PUPDR4_0);

    SET_BIT(GPIOD->MODER, GPIO_MODER_MODE5_0);
    CLEAR_BIT(GPIOD->OTYPER, GPIO_OTYPER_OT_5);
    SET_BIT(GPIOD->OSPEEDR, GPIO_OSPEEDER_OSPEEDR5_0);
    CLEAR_BIT(GPIOD->PUPDR, GPIO_PUPDR_PUPDR5_0);
}