#include <init.h>

void GPIO_Ini(void){
        //led pin B14
        *(uint32_t*)(0x40020400UL) |= 0x10000000UL;
        *(uint32_t*)(0x40020400UL + 0x04UL) |= 0x0000UL;
        *(uint32_t*)(0x40020400UL + 0x08UL) |= 0x10000000UL;
        *(uint32_t*)(0x40020400UL + 0x0CUL) |= 0x0000UL; 
        *(uint32_t*)(0x40020400UL + 0x18UL) |= 0x40000000UL;
}

void GPIO_Ini_Self_Def(void){
        // led pin B0
        GPIOB_MODER |= GPIOB_MODE_PIN0_OUT;
        GPIOB_OTYPER |= GPIOB_OTYPE_PIN0_PP;
        GPIOB_OSPEEDR |= GPIOB_OSPEED_PIN0_MID;
        GPIOB_PUPDR |= GPIOB_PUPDR_PIN0_NOPUPD;
        GPIOB_BSRR |= GPIOB_BSRR_PIN0_RESET;
}

void GPIO_Ini_CMSIS(void){
        SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN);
        // button pin C0
        CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE0_0);
        CLEAR_BIT(GPIOC->OTYPER, GPIO_OTYPER_OT_0);
        CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);
        CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR0_0);

        // SET_BIT(GPIOB->MODER, GPIO_MODER_MODE0_0);
        // CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_0);
        // SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);
        // CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR0_0);
        // led pin B7
        SET_BIT(GPIOB->MODER, GPIO_MODER_MODE7_0);
        CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_7);
        SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_0);
        CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR7_0);

        // SET_BIT(GPIOB->MODER, GPIO_MODER_MODE14_0);
        // CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_14);
        // SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR14_0);
        // CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR7_0);
}